CREATE TABLE IF NOT EXISTS `sys_user` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `username` varchar(50) NOT NULL COMMENT '用户名',
  `password` varchar(100) NOT NULL COMMENT '密码',
  `real_name` varchar(50) NOT NULL COMMENT '真实姓名',
  `phone` varchar(20) COMMENT '手机号',
  `role_code` varchar(20) NOT NULL COMMENT '角色编码: PASTURE牧场, LAB化验员, DRIVER司机, ADMIN管理员, LAB_SUPERVISOR化验室主管, QUALITY_SUPERVISOR质量主管, PASTURE_SUPERVISOR牧场主管, DEPARTMENT_MANAGER部门经理, QUALITY_DIRECTOR质量总监, ON_SITE_SUPERVISOR现场主管',
  `pasture_id` bigint COMMENT '所属牧场ID',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态: 0禁用, 1启用',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除: 0未删除, 1已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_username` (`username`),
  KEY `idx_role` (`role_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

CREATE TABLE IF NOT EXISTS `pasture` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `pasture_code` varchar(50) NOT NULL COMMENT '牧场编码',
  `pasture_name` varchar(100) NOT NULL COMMENT '牧场名称',
  `address` varchar(255) COMMENT '地址',
  `contact_person` varchar(50) COMMENT '联系人',
  `contact_phone` varchar(20) COMMENT '联系电话',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态: 0禁用, 1启用',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除: 0未删除, 1已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pasture_code` (`pasture_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='牧场表';

CREATE TABLE IF NOT EXISTS `milk_tank` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tank_code` varchar(50) NOT NULL COMMENT '奶罐编号',
  `tank_name` varchar(100) COMMENT '奶罐名称',
  `capacity` decimal(10,2) NOT NULL COMMENT '容量(升)',
  `current_volume` decimal(10,2) NOT NULL DEFAULT 0 COMMENT '当前存量(升)',
  `tank_status` varchar(20) NOT NULL DEFAULT 'IDLE' COMMENT '状态: IDLE空闲, LOADING接奶中, PENDING_TEST待检测, TESTED检测完成, LOADED已装车, PENDING_CLEAN待清洗',
  `last_clean_time` datetime COMMENT '上次清洗时间',
  `current_batch_id` bigint COMMENT '当前批次ID',
  `pasture_id` bigint NOT NULL COMMENT '所属牧场ID',
  `remark` varchar(255) COMMENT '备注',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除: 0未删除, 1已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tank_code` (`tank_code`),
  KEY `idx_pasture` (`pasture_id`),
  KEY `idx_status` (`tank_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='奶罐表';

CREATE TABLE IF NOT EXISTS `milk_batch` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `batch_no` varchar(50) NOT NULL COMMENT '批次号',
  `pasture_id` bigint NOT NULL COMMENT '牧场ID',
  `tank_id` bigint NOT NULL COMMENT '奶罐ID',
  `milking_start_time` datetime COMMENT '挤奶开始时间',
  `milking_end_time` datetime COMMENT '挤奶结束时间',
  `milk_volume` decimal(10,2) NOT NULL COMMENT '奶量(升)',
  `milk_temperature` decimal(5,2) COMMENT '奶温(℃)',
  `cow_count` int COMMENT '头数',
  `milker_id` bigint COMMENT '挤奶员ID',
  `batch_status` varchar(20) NOT NULL DEFAULT 'MILKING' COMMENT '状态: MILKING挤奶中, PENDING_TEST待检测, TEST_PASSED检测通过, TEST_FAILED检测不合格, LOADED已装车, REJECTED已拒收',
  `remark` varchar(255) COMMENT '备注',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除: 0未删除, 1已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_batch_no` (`batch_no`),
  KEY `idx_pasture` (`pasture_id`),
  KEY `idx_tank` (`tank_id`),
  KEY `idx_status` (`batch_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='挤奶批次表';

CREATE TABLE IF NOT EXISTS `antibiotic_test` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `test_no` varchar(50) NOT NULL COMMENT '检测单号',
  `batch_id` bigint NOT NULL COMMENT '批次ID',
  `tank_id` bigint NOT NULL COMMENT '奶罐ID',
  `pasture_id` bigint NOT NULL COMMENT '牧场ID',
  `lab_id` bigint COMMENT '化验员ID',
  `test_type` varchar(50) NOT NULL COMMENT '检测类型: 青霉素类, 头孢类, 四环素类等',
  `test_method` varchar(50) COMMENT '检测方法: 快检卡, 仪器检测等',
  `test_result` varchar(20) NOT NULL COMMENT '检测结果: PASSED合格, FAILED不合格',
  `test_value` varchar(50) COMMENT '检测值',
  `test_time` datetime NOT NULL COMMENT '检测时间',
  `is_locked` tinyint NOT NULL DEFAULT 0 COMMENT '是否锁定: 0未锁定, 1已锁定(装车后不可修改)',
  `approve_status` varchar(20) NOT NULL DEFAULT 'DRAFT' COMMENT '审批状态: DRAFT草稿, PENDING审批中, APPROVED已审批, REJECTED已驳回',
  `approver_id` bigint COMMENT '审批人ID',
  `approve_time` datetime COMMENT '审批时间',
  `approve_remark` varchar(255) COMMENT '审批意见',
  `remark` varchar(255) COMMENT '备注',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除: 0未删除, 1已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_test_no` (`test_no`),
  KEY `idx_batch` (`batch_id`),
  KEY `idx_tank` (`tank_id`),
  KEY `idx_status` (`test_result`),
  KEY `idx_approve` (`approve_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='抗生素检测表';

CREATE TABLE IF NOT EXISTS `loading_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `loading_no` varchar(50) NOT NULL COMMENT '装车单号',
  `batch_id` bigint NOT NULL COMMENT '批次ID',
  `tank_id` bigint NOT NULL COMMENT '奶罐ID',
  `pasture_id` bigint NOT NULL COMMENT '牧场ID',
  `driver_id` bigint NOT NULL COMMENT '司机ID',
  `truck_no` varchar(50) COMMENT '车牌号',
  `load_volume` decimal(10,2) NOT NULL COMMENT '装车量(升)',
  `load_temperature` decimal(5,2) COMMENT '装车时奶温(℃)',
  `load_time` datetime NOT NULL COMMENT '装车时间',
  `destination` varchar(255) COMMENT '目的地',
  `arrival_time` datetime COMMENT '到达时间',
  `loading_status` varchar(20) NOT NULL DEFAULT 'LOADED' COMMENT '状态: LOADED已装车, IN_TRANSIT运输中, ARRIVED已到达',
  `remark` varchar(255) COMMENT '备注',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除: 0未删除, 1已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_loading_no` (`loading_no`),
  KEY `idx_batch` (`batch_id`),
  KEY `idx_driver` (`driver_id`),
  KEY `idx_status` (`loading_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='装车记录表';

CREATE TABLE IF NOT EXISTS `tank_cleaning` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `cleaning_no` varchar(50) NOT NULL COMMENT '清洗单号',
  `tank_id` bigint NOT NULL COMMENT '奶罐ID',
  `pasture_id` bigint NOT NULL COMMENT '牧场ID',
  `operator_id` bigint COMMENT '操作员ID',
  `cleaning_start_time` datetime NOT NULL COMMENT '清洗开始时间',
  `cleaning_end_time` datetime COMMENT '清洗结束时间',
  `cleaning_method` varchar(50) COMMENT '清洗方式',
  `cleaning_agent` varchar(50) COMMENT '清洗剂',
  `water_temperature` decimal(5,2) COMMENT '水温(℃)',
  `is_qualified` tinyint COMMENT '是否合格: 0不合格, 1合格',
  `checker_id` bigint COMMENT '检查人ID',
  `check_time` datetime COMMENT '检查时间',
  `remark` varchar(255) COMMENT '备注',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除: 0未删除, 1已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cleaning_no` (`cleaning_no`),
  KEY `idx_tank` (`tank_id`),
  KEY `idx_status` (`is_qualified`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='奶罐清洗表';

CREATE TABLE IF NOT EXISTS `reject_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `reject_no` varchar(50) NOT NULL COMMENT '拒收单号',
  `batch_id` bigint NOT NULL COMMENT '批次ID',
  `tank_id` bigint NOT NULL COMMENT '奶罐ID',
  `pasture_id` bigint NOT NULL COMMENT '牧场ID',
  `test_id` bigint COMMENT '检测单ID',
  `reject_type` varchar(50) NOT NULL COMMENT '拒收类型: TEST_FAILED检测不合格, TANK_DIRTY奶罐未清洗, OTHER其他',
  `reject_reason` varchar(500) NOT NULL COMMENT '拒收原因',
  `reject_time` datetime NOT NULL COMMENT '拒收时间',
  `operator_id` bigint COMMENT '操作人ID',
  `handler_id` bigint COMMENT '处理人ID',
  `handle_status` varchar(20) NOT NULL DEFAULT 'PENDING' COMMENT '处理状态: PENDING待处理, HANDLING处理中, RESOLVED已解决',
  `handle_result` varchar(500) COMMENT '处理结果',
  `handle_time` datetime COMMENT '处理时间',
  `remark` varchar(255) COMMENT '备注',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除: 0未删除, 1已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_reject_no` (`reject_no`),
  KEY `idx_batch` (`batch_id`),
  KEY `idx_type` (`reject_type`),
  KEY `idx_handle_status` (`handle_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='拒收记录表';
